### ISSUE TITLE
How to set sort order and position on list for categories and sites in qpages?

### ISSUE THREAD

**Issue by panwac** [redmexico/qpages#5]
I'm trying to find a possibility to change a sort order for pages (categories too). In admin panel there is an option "Set order", but I don't see any effect of that. Any suggestions? ;)

Vbr

Piotr

**Comment by bitcero** [comment]
I'll try to add this feature for next release...

**Comment by panwac** [comment]
O.K. Thx for the answer. I'll be waiting for that :)
