### ISSUE TITLE
no muestra los contenidos con el nuevo rmcommon

### ISSUE THREAD

**Issue by markosc** [redmexico/qpages#6]
si bien crea contenidos pero no se puede visualizar ya sea activando o desactivando el las url amigables similar sucede con "docs"...

**Comment by bitcero** [comment]
verificando...

**Comment by bitcero** [comment]
No he podido reproducir el error. ¿Puede proporcionar más información?

* versiones de XOOPS, rmcommon y xthemes
* Registro del depurador (xoops debug)

**Comment by markosc** [comment]
PHP
5.4.45
MySQL
5.5.45
`http://hwtotal.com/contenido/como-grabar-imagen-del-sistema-operativo-en-un-usb/`
no sale errores
aparece el enlace para ir nuevamente pero al hacer click no se muestra el contenido

**Comment by bitcero** [comment]
¿No aparecen errores en el debug de xoops?

**Comment by markosc** [comment]
no errores (0)

**Comment by markosc** [comment]
Desactivando La Url Amigable puedo ver su contenido es decir con los enlaces "/page.php?page="

**Comment by bitcero** [comment]
¿Puedes verificar que este activa la opción "Activar reescritura de URLs" en la configuración de Common Utilities?

**Comment by markosc** [comment]
lo acabo de activar T_T
que roche xD, ya que con mywords no es necesario activar esa opción
Gracias.

**Comment by bitcero** [comment]
Corregido este problema...
